### ISSUE TITLE
HHVM crashed while loading dokuwiki syntax page

### ISSUE THREAD

**Issue by matzekuh** [splitbrain/dokuwiki#1030]
Hello,

the dokuwiki syntax page is causing hhvm (http://hhvm.com/) to crash. I found out that the syntax snippet

```
<html>
<span>some content</span>
</html>
```

is causing the crash.

I want to figure out which php functions actually cause the issue. I sent the debug output via mail.

**Comment by splitbrain** [comment]
Just a note: we do not officially support HHVM currently. Mainly because our test suit doesn't run at all on HHVM and we have no idea why (see http://stackoverflow.com/questions/27822712/how-to-debug-a-failing-hhvm-phpunit). But I'm more than happy to accept any pull requests that make DokuWiki run better on HHVM.

**Comment by splitbrain** [comment]
additionally please pastebin or gist the debug output and link it here for availability to a broader audience

**Comment by matzekuh** [comment]
https://gist.github.com/d4b00eec3e0fa53204c4.git

**Comment by matzekuh** [comment]
That's the hhvm stacktrace.

```
Host: ####
ProcessID: 30201
ThreadID: 7f525f7ff700
ThreadPID: 30216
Name: unknown program
Type: Segmentation fault
Runtime: hhvm
Version: heads/master-0-g163b2627434f48963ba334d90f668ffbc96e067e
DebuggerCount: 0

Server: ####
ThreadType: Web Request
Server_SERVER_NAME: ####
URL: /wiki/doku.php?id=wiki:syntax

# 0  bt_handler at /tmp/tmp.58XxoBHyUx/hphp/runtime/base/crash-reporter.cpp:71
```

**Comment by Chris--S** [comment]
After looking at the [hack unsupported php page](http://docs.hhvm.com/manual/en/hack.unsupported.php) I think there are a fair few of the mentioned PHP features in DokuWiki.  Most likely:
* '@' error suppression operator
* variable references, e.g function foo(&$p)
* global keyword
* empty list(,) parameters

And possibly:
* if: endif;
* and, or
* undefined variables

**Comment by splitbrain** [comment]
@Chris--S hack != PHP. hack is a subset of PHP, but HHVM can do both and should be able to run DokuWiki.

**Comment by Klap-in** [comment]
Test suite is fixed for HHVM since 32c7ba22db35fd22aed87fb31984069873cefc4f
Tests live at https://travis-ci.org/splitbrain/dokuwiki

**Comment by splitbrain** [comment]
Keep in mind that travis is running an older version of phpunit and HHVM so tests still fail at travis

**Comment by splitbrain** [comment]
I'm closing this. DokuWiki probably "mostly" works on a modern HHVM but we will probably never officially support it.

I'm happy to accept patches to the core and the test suite for HHVM compatibility.
