### ISSUE TITLE
Greebo: new code in parser/xhtml.php results in error message with include plugin

### ISSUE THREAD

**Issue by turnermm** [splitbrain/dokuwiki#2326]
New Code in Greebo, parse/xhtml.php:
```
        if (!is_array($data)) {
            msg(
                sprintf(
                    'startSectionEdit: $data "%s" is NOT an array! One of your plugins needs an update.',
                    hsc((string) $data)
                ), -1
            );
ll. 79-86 parser/xhtml.php
```
This new code outputs the error message in response to include/syntax/wrap.php, ll. 39-46.  No error is issued to the server error log.  First reported on the forum: https://forum.dokuwiki.org/thread/15764.  This does not happen in Frusterick M (or earlier).

**Comment by kvnyang** [comment]
My dokuwiki shows the following error at the top of the welcome page every time I log out and log in:
```
startSectionEdit: $data "plugin_include_start" is NOT an array! One of your plugins needs an update.
startSectionEdit: $data "plugin_include_end" is NOT an array! One of your plugins needs an update.
startSectionEdit: $data "plugin_include_start" is NOT an array! One of your plugins needs an update.
...
```

**Comment by selfthinker** [comment]
As the message says, the plugin "needs an update". This has already been fixed in the include plugin (dokufreaks/plugin-include#224), please update the plugin.
It's mentioned in the [changelog](https://www.dokuwiki.org/changes#release_2018-04-22_release_greebo), see #2290 for more info.

**Comment by turnermm** [comment]
I think the issue yesterday was that the update wasn’t showing up in the extension manager.

**Comment by tmo26** [comment]
Re-Installing the include plugin via the Extension Manager solved the _"plugin_include_start" is NOT an array!_ error, but it still doesn't show up as updatable.

Even after re-installing it reports _"Installed version:   2017-08-24"_

**Comment by micgro42** [comment]
While the include plugin already contains the fixes, I just now updated its version number. Hopefully it will start showing up as updateable to people.

**Comment by tmo26** [comment]
Yes, now it does show up as updatable.
Thanks for fixing this!
