### ISSUE TITLE
Fix/Update/Delete extension pages

### ISSUE THREAD

**Issue by splitbrain** [splitbrain/dokuwiki#2370]
We have quite a few plugins and templates that have no or broken downloads or are documented on pages in the wrong namespace.

Thes extension pages should be checked manually to see if there are any alternative downloads (eg. mentioned as a comment or its a bundled plugin). If no sensible download can be found, I vote for deleting the extension page completely.

Please refer to the [Plugin Repository Manual](https://www.dokuwiki.org/plugin:repository:manual) to learn how the extension markup works.

Below are all extensions that have been recently shown problems:

- [ ] plugin/ruby     no download URL
- [ ] plugin/tab      no download URL
- [ ] plugin/phpwikify        no download URL
- [ ] auth:django     Unknonw type
- [ ] frplugin:bureaucracy    Unknonw type
- [ ] plugin/authpdo  no download URL
- [ ] plugin/nodisp   no download URL
- [ ] template/a_new_day      no download URL
- [ ] plugin/styling  no download URL
- [ ] plugin/captchalogin     no download URL
- [ ] plugin/authplain        no download URL
- [ ] plugin/extension        no download URL
- [ ] plugin/niconico no download URL
- [ ] plugin/acl      no download URL
- [ ] template/dokuwiki       no download URL
- [ ] plugin/authldap no download URL
- [ ] plugin/authad   no download URL
- [ ] plugin/config   no download URL
- [ ] plugin/info     no download URL
- [ ] plugin/usermanager      no download URL
- [ ] plugin/sphinxsearch     no download URL
- [ ] plugin/authmysql        no download URL
- [ ] plugin/authpgsql        no download URL
- [ ] plugin/workflow no download URL
- [ ] plugin/revert   no download URL
- [ ] plugin/popularity       no download URL
- [ ] plugin/anchor   no download URL
- [ ] plugin/fbde     no download URL
- [ ] plugin/wikindx  no download URL
- [ ] plugin/remust   no download URL
- [ ] plugin/svnmod   no download URL
- [ ] plugin/pastdate no download URL
- [ ] template/darkclean      no download URL
- [ ] plugin/s5reloaded       no download URL
- [ ] plugin/movedel  no download URL
- [ ] plugin/safefnrecode     no download URL
- [ ] plugin/testing  no download URL
- [ ] plugin/flmod    no download URL
- [ ] plugin/piwik    no download URL
- [ ] plugin/regexreplacer    no download URL
- [ ] template/knotux no download URL
- [ ] plugin/bliki    no download URL
- [ ] plugin/agenda   no download URL
- [ ] plugin/codepad  no download URL
- [ ] plugin/asciimathml      no download URL
- [ ] plugin/asciisvg no download URL
- [ ] plugin/ical     no download URL
- [ ] plugin/simpleweather    no download URL
- [ ] plugin/rmt      no download URL
- [ ] plugin/timeline2        no download URL
- [ ] plugin/svnlog   no download URL
- [ ] plugin/webthumbs        no download URL
- [ ] plugin/floatdiv no download URL
- [ ] plugin/skydoku  no download URL
- [ ] plugin/screenplay       no download URL
- [ ] plugin/linkbonus        no download URL
- [ ] plugin/dokureflection   no download URL
- [ ] plugin/previous no download URL
- [ ] template/simple no download URL
- [ ] plugin/dokuwikitweet    no download URL
- [ ] plugin/menupopup        no download URL
- [ ] plugin/exttab2  no download URL
- [ ] template/imm    no download URL
- [ ] plugin/alignment        no download URL
- [ ] plugin/nocode   no download URL
- [ ] plugin/noticeboard      no download URL
- [ ] plugin/pdfbook  no download URL
- [ ] plugin/videogg  no download URL
- [ ] template/dokumobile     no download URL
- [ ] plugin/wpre     no download URL
- [ ] plugin/mailrss  no download URL
- [ ] plugin/geogebra2        no download URL
- [ ] plugin/shibbolethauth   no download URL
- [ ] plugin/refererremove    no download URL
- [ ] plugin/hidetext no download URL
- [ ] plugin/mypage   no download URL
- [ ] plugin/class    no download URL
- [ ] plugin/editformhelppage no download URL
- [ ] template/beaufort       no download URL
- [ ] plugin/tablemath        no download URL
- [ ] plugin/dataloop no download URL
- [ ] plugin/countdowntimer   no download URL
- [ ] plugin/autoincludeindex no download URL
- [ ] plugin/webcomics        no download URL
- [ ] plugin/noblankcells     no download URL
- [ ] plugin/garfield no download URL
- [ ] plugin/classificationbanner     no download URL
- [ ] plugin/keywordvoting    no download URL
- [ ] plugin/countdowndisplay no download URL
- [ ] plugin/ganalytics       no download URL
- [ ] plugin/scrum    no download URL
- [ ] template/desert no download URL
- [ ] plugin/modalpopup       no download URL
- [ ] plugin/ahrefmenu        no download URL
- [ ] plugin/progressbar      no download URL
- [ ] plugin/html2pdf no download URL
- [ ] plugin/delicious        no download URL
- [ ] plugin/revlink  no download URL
- [ ] plugin/bookmarkfile     no download URL
- [ ] plugin/fckw     no download URL
- [ ] plugin/tbt      no download URL
- [ ] plugin/dailymotion      no download URL
- [ ] plugin/dailymotion_videozap     no download URL
- [ ] plugin/verinfo  no download URL
- [ ] plugin/routeplaner      no download URL
- [ ] plugin/webalbum no download URL
- [ ] plugin/inserticon       no download URL
- [ ] template/usable no download URL
- [ ] plugin/pchart   no download URL
- [ ] template/ameoto no download URL
- [ ] template/arctic_dark    no download URL
- [ ] template/dokuwiki_dark  no download URL
- [ ] plugin/wikisign no download URL
- [ ] plugin/caltable no download URL
- [ ] plugin/bashorg  no download URL
- [ ] plugin/oembed   no download URL
- [ ] plugin/mathoperation    no download URL
- [ ] plugin/wysiwyg_nicedit  no download URL
- [ ] plugin/vote     no download URL
- [ ] template/lmcstyle       no download URL
- [ ] plugin/database no download URL
- [ ] plugin/woot     no download URL
- [ ] plugin/showfile no download URL
- [ ] plugin/pdfex    no download URL
- [ ] template/masa   no download URL
- [ ] plugin/friendfeed       no download URL
- [ ] plugin/dl       no download URL
- [ ] template/influence      no download URL
- [ ] plugin/divalign no download URL
- [ ] plugin/pxxo     no download URL
- [ ] plugin/chart    no download URL
- [ ] plugin/gitlink  no download URL
- [ ] plugin/relativelinks    no download URL
- [ ] plugin/harvcite no download URL
- [ ] plugin/kixovar  no download URL
- [ ] plugin/pagespace        no download URL
- [ ] plugin/permissionstyles no download URL
- [ ] plugin/blip     no download URL
- [ ] template/mmkanso        no download URL
- [ ] template/phosphor       no download URL
- [ ] plugin/imstatus no download URL
- [ ] plugin/nroff    no download URL
- [ ] plugin/sos      no download URL
- [ ] plugin/ping     no download URL
- [ ] plugin/traceroute       no download URL
- [ ] plugin/dnsbl    no download URL
- [ ] plugin/whois    no download URL
- [ ] plugin/btable   no download URL
- [ ] plugin/heise    no download URL
- [ ] plugin/visio    no download URL
- [ ] plugin/phpimplicitnocache       no download URL
- [ ] plugin/censure  no download URL
- [ ] template/slaad  no download URL
- [ ] plugin/galleryv1.5      no download URL
- [ ] plugin/pgnviewer        no download URL
- [ ] template/mmclean        no download URL
- [ ] template/mmzire no download URL
- [ ] plugin/refworks no download URL
- [ ] plugin/truetable        no download URL
- [ ] plugin/importanttext    no download URL
- [ ] plugin/sevenload        no download URL
- [ ] plugin/google_video     no download URL
- [ ] plugin/rdplink  no download URL
- [ ] plugin/htag     no download URL
- [ ] template/minimal_mobile no download URL
- [ ] plugin/drop_all no download URL
- [ ] plugin/userhomepages    no download URL
- [ ] plugin/drop_me  no download URL
- [ ] plugin/dokukiwix        no download URL
- [ ] plugin/youtubev2        no download URL
- [ ] plugin/div_span_shorthand       no download URL
- [ ] plugin/layout   no download URL
- [ ] template/gina-fso       no download URL
- [ ] plugin/guestbook        no download URL
- [ ] template/battlehorse    no download URL
- [ ] plugin/geourl   no download URL
- [ ] plugin/template_switcher        no download URL
- [ ] plugin/linkext  no download URL
- [ ] plugin/french_typography        no download URL
- [ ] plugin/ltr      no download URL
- [ ] template/sidebar_theme  no download URL
- [ ] plugin/gcalendar        no download URL
- [ ] plugin/importoldindex   no download URL
- [ ] template/sambar no download URL
- [ ] plugin/importoldchangelog       no download URL
- [ ] plugin/logoutconvenience        no download URL
- [ ] template/ex     no download URL
- [ ] plugin/bibtex   no download URL
- [ ] plugin/incl_form        no download URL
- [ ] plugin/xterm    no download URL
- [ ] plugin/amazon_heavy     no download URL
- [ ] plugin/space    no download URL
- [ ] plugin/userxtension     no download URL
- [ ] plugin/anormal_tracker  no download URL
- [ ] plugin/linkway  no download URL
- [ ] plugin/flickr   no download URL
- [ ] plugin/markdown no download URL
- [ ] plugin/phpinc   no download URL
- [ ] plugin/docbook  no download URL
- [ ] plugin/toplist  no download URL
- [ ] plugin/freemind no download URL
- [ ] plugin/signature        no download URL
- [ ] template/cherokee-based no download URL
- [ ] template/sxs    no download URL
- [ ] plugin/photoblox        no download URL
- [ ] plugin/applet   no download URL
- [ ] plugin/important_paragraf       no download URL
- [ ] plugin/inandout no download URL
- [ ] plugin/includeuserpage  no download URL
- [ ] template/amanuensis     no download URL
- [ ] plugin/boxes_mod        no download URL
- [ ] plugin/backlinks        no download URL
- [ ] plugin/video    no download URL
- [ ] plugin/draw     no download URL
- [ ] plugin/skill    no download URL
- [ ] plugin/content  no download URL
- [ ] plugin/dirlisting       no download URL
- [ ] plugin/darcs    no download URL
- [ ] plugin/template no download URL
- [ ] plugin/date_time        no download URL
- [ ] plugin/definitions      no download URL
- [ ] plugin/term     no download URL
- [ ] plugin/newpage  no download URL
- [ ] plugin/recent   no download URL
- [ ] plugin/gnuplot  no download URL
- [ ] plugin/sparkline        no download URL
- [ ] plugin/localdate        no download URL
- [ ] plugin/inline_folding2  no download URL
- [ ] plugin/inline_folding   no download URL
- [ ] plugin/side_note        no download URL
- [ ] plugin/isbn     no download URL
- [ ] plugin/wp_most_recent   no download URL
- [ ] playground:playground7  Unknonw type
- [ ] plugin/plugin   no download URL
- [ ] plugin/flowcharts       Download not an archive: 
- [ ] plugin/tablecalc        Download not an archive: 
- [ ] plugin/jenkins  Download failed. Status 404
- [ ] plugin/yuml     Download not an archive: 
- [ ] plugin/stdokuwikiconnector      Header does not match it's checksum
- [ ] plugin/remotelistnamespace      Download failed. Status 404
- [ ] plugin/interwikiformatting      Download failed. Status 404
- [ ] plugin/forcessllogin    Download failed. Status 502
- [ ] plugin/facebookevents   Header does not match it's checksum
- [ ] template/arctic Download failed. Status 502
- [ ] template/dokubook       Download failed. Status 502
- [ ] plugin/components       Download not an archive: 
- [ ] plugin/apidoc   Header does not match it's checksum
- [ ] plugin/mapillary        Header does not match it's checksum
- [ ] plugin/subconfhelper    Download failed. Status 502
- [ ] plugin/templateconfhelper       Download failed. Status 502
- [ ] plugin/dokuwiki-webcomics       Download failed. Status 404
- [ ] plugin/youtrack Header does not match it's checksum
- [ ] plugin/geophp   Header does not match it's checksum
- [ ] plugin/manner   Download not an archive: 
- [ ] plugin/easypaste        Download not an archive: 
- [ ] plugin/headerfooter     Download not an archive: 
- [ ] plugin/indexeverywhere  Download not an archive: 
- [ ] plugin/duoshuo-dokuwiki Download failed. Status 404
- [ ] template/dokui  Header does not match it's checksum
- [ ] plugin/dataplot Download not an archive: 
- [ ] plugin/txt2tags Download not an archive: 
- [ ] template/greensteel     Download not an archive: 
- [ ] plugin/p2ilinkaction    Header does not match it's checksum
- [ ] template/mnml-blog      Download not an archive: 
- [ ] template/monobook       Download not an archive: 
- [ ] template/prsnl10        Download not an archive: 
- [ ] template/vector Download not an archive: 
- [ ] plugin/jcapture Download not an archive: 
- [ ] plugin/podcast  Download failed. Status 502
- [ ] template/sugna  Download failed. Status 404
- [ ] plugin/lvhpacket        Header does not match it's checksum
- [ ] plugin/unameban Download not an archive: 
- [ ] plugin/userpoll Download not an archive: 
- [ ] plugin/since    Download not an archive: 
- [ ] plugin/zotero   Download not an archive: 
- [ ] plugin/projects Header does not match it's checksum
- [ ] template/scanlines      Header does not match it's checksum
- [ ] plugin/tcycle   Download not an archive: 
- [ ] plugin/bible    Download failed. Status 404
- [ ] plugin/facebookwall     Header does not match it's checksum
- [ ] template/wikimagination Download failed. Status 404
- [ ] template/mystyle        Download not an archive: 
- [ ] template/writers        Download not an archive: 
- [ ] plugin/reproduce        Download failed. Status 404
- [ ] template/arctic-mbo     Header does not match it's checksum
- [ ] plugin/facebooklike     Download failed. Status 404
- [ ] plugin/jquery-syntax    Download failed. Status 404
- [ ] plugin/colortag Download not an archive: 
- [ ] plugin/facebookalbum    Header does not match it's checksum
- [ ] plugin/macros   Download failed. Status 404
- [ ] template/spacedok       Download not an archive: 
- [ ] template/lcars  Download failed. Status 404
- [ ] plugin/ryubin   Header does not match it's checksum
- [ ] plugin/icalendar        Download failed. Status 404
- [ ] plugin/daftdrafts       Download failed. Status 404
- [ ] plugin/inlineeditor     Header does not match it's checksum
- [ ] plugin/mindmap  Header does not match it's checksum
- [ ] plugin/smartcache       Header does not match it's checksum
- [ ] plugin/autotweet        Header does not match it's checksum
- [ ] template/roundtheme     Download failed. Status 404
- [ ] plugin/onlineordering   Header does not match it's checksum
- [ ] plugin/googleplusone    Download failed. Status 404
- [ ] plugin/jsmath   Download failed. Status 404
- [ ] plugin/googlemap3       Download not an archive: 
- [ ] plugin/autlogin Download failed. Status 404
- [ ] plugin/lampshade        Download failed. Status 404
- [ ] template/my_little_forum        Header does not match it's checksum
- [ ] plugin/codebutton2      Download failed. Status 404
- [ ] plugin/quiz     Download not an archive: 
- [ ] template/dynamic_template       Header does not match it's checksum
- [ ] plugin/aclauditor       Download not an archive: 
- [ ] plugin/newsboard        Download failed. Status 404
- [ ] plugin/pagebox  Download failed. Status 404
- [ ] plugin/wikicalendar     Download not an archive: 
- [ ] plugin/quickedit        Download failed. Status 404
- [ ] template/a_dark_divide  Download not an archive: 
- [ ] plugin/syntaxhighlighter2       Download not an archive: 
- [ ] plugin/acronym4glossary Download failed. Status 404
- [ ] plugin/sidebarng        Download not an archive: 
- [ ] plugin/vamr     Unexpected length of header
- [ ] plugin/stats    Header does not match it's checksum
- [ ] plugin/dokugource       Download not an archive: 
- [ ] plugin/mantis   Download failed. Status 401
- [ ] plugin/cronojob Download failed. Status 404
- [ ] plugin/gist     Download not an archive: 
- [ ] plugin/multipoll        Download not an archive: 
- [ ] plugin/showinitpage     Download failed. Status 404
- [ ] template/dokuxp Download not an archive: 
- [ ] plugin/jmol2    Download failed. Status 404
- [ ] plugin/translator       Download failed. Status 404
- [ ] plugin/geogebra Download failed. Status 404
- [ ] plugin/mundart  Download failed. Status 401
- [ ] plugin/highlightjs      Download failed. Status 404
- [ ] plugin/itrackviewer     Download failed. Status 404
- [ ] plugin/swfobject        Download failed. Status 404
- [ ] plugin/usersubscriptions        Download not an archive: 
- [ ] plugin/timeline Download not an archive: 
- [ ] plugin/panorama Download failed. Status 404
- [ ] plugin/qrcode   Download failed. Status 404
- [ ] plugin/sidebar  Download failed. Status 404
- [ ] plugin/adminhomepage    Download not an archive: 
- [ ] plugin/cite     Download not an archive: 
- [ ] plugin/displaywikipage  Download not an archive: 
- [ ] plugin/referrers        Download not an archive: 
- [ ] plugin/jalbum   Download failed. Status 404
- [ ] plugin/clearfloat       Download not an archive: 
- [ ] plugin/gpsies   Download not an archive: 
- [ ] plugin/gtd      Download not an archive: 
- [ ] plugin/lastfm   Download not an archive: 
- [ ] plugin/querychangelog   Download failed. Status 404
- [ ] plugin/lists_improved   Download failed. Status 404
- [ ] plugin/ondeniedlogin    Download failed. Status 404
- [ ] plugin/replace  Download failed. Status 404
- [ ] plugin/svgimg2  Download failed. Status 404
- [ ] plugin/usercss  Download not an archive: 
- [ ] plugin/frootysearch     Download failed. Status 404
- [ ] plugin/freesync Header does not match it's checksum
- [ ] plugin/dlcount  Download failed. Status 404
- [ ] plugin/hyphenation      Download failed. Status 404
- [ ] plugin/userannotations  Download failed. Status 404
- [ ] plugin/codehighlight    Download failed. Status 404
- [ ] plugin/operawidget      Download failed. Status 404
- [ ] plugin/uparrow  Download not an archive: 
- [ ] plugin/jquery   Download failed. Status 404
- [ ] plugin/bahnde   Download failed. Status 404
- [ ] plugin/qstat    Download failed. Status 404
- [ ] plugin/zul      Download failed. Status 404
- [ ] plugin/userfly  Download failed. Status 404
- [ ] plugin/indexmenu2       Download failed. Status 500
- [ ] plugin/random_page      Header does not match it's checksum
- [ ] plugin/bookmarkme       Download failed. Status 500
- [ ] template/zero   Header does not match it's checksum
- [ ] plugin/stars    Download failed. Status 404
- [ ] plugin/toursprung       Download failed. Status 404
- [ ] plugin/underconstruction        Download failed. Status 404
- [ ] plugin/userspagecreate  Download not an archive: 
- [ ] plugin/autostart        Download failed. Status 404
- [ ] plugin/contact  Download not an archive: 
- [ ] plugin/fontsize Download failed. Status 404
- [ ] plugin/flowplay2        Download failed. Status 404
- [ ] plugin/linkmanager      Download not an archive: 
- [ ] plugin/hcalendar        Download failed. Status 404
- [ ] plugin/code3    Download failed. Status 500
- [ ] plugin/reliwa   Download failed. Status 404
- [ ] plugin/google_adsense2  Download not an archive: 
- [ ] plugin/wysiwyg  Download not an archive: 
- [ ] plugin/keywords Download failed. Status 500
- [ ] plugin/abb      Download failed. Status 404
- [ ] template/dokubook2      Header does not match it's checksum
- [ ] plugin/pagetemplate     Download not an archive: 
- [ ] plugin/ticketlinker     Header does not match it's checksum
- [ ] plugin/chord    Download not an archive: 
- [ ] plugin/googleads        Download not an archive: 
- [ ] plugin/remotescript     Download failed. Status 500
- [ ] plugin/format   Download failed. Status 404
- [ ] plugin/distribute       Download not an archive: 
- [ ] plugin/textile2 Header does not match it's checksum
- [ ] plugin/websvn   Download not an archive: 
- [ ] plugin/shortcut Download failed. Status 500
- [ ] plugin/fullindex        Download failed. Status 404
- [ ] plugin/virtualkeyboard  Download failed. Status 500
- [ ] plugin/chat     Download not an archive: 
- [ ] plugin/livepreview      Download failed. Status 500
- [ ] plugin/pageindex        Header does not match it's checksum
- [ ] plugin/grensladawritezor        Download not an archive: 
- [ ] plugin/zip      Download not an archive: 
- [ ] plugin/socialmark       Download not an archive: 
- [ ] plugin/isns     Download not an archive: 
- [ ] plugin/commentsrc       Download not an archive: 
- [ ] plugin/multinamespace   Download not an archive: 
- [ ] plugin/ifauth   Download not an archive: 
- [ ] plugin/bookmark Download not an archive: 
- [ ] plugin/externallink     Download not an archive: 
- [ ] plugin/fortune  Download not an archive: 
- [ ] template/nucleus        Header does not match it's checksum
- [ ] plugin/timer    Download not an archive:

**Comment by LarsGit223** [comment]
I checked plugin/styling as it is bundled with DokuWiki :grin:

**Comment by LarsGit223** [comment]
@leeyc0: on the plugin page niconico is marked as deprecated/discontinued. Would it be fine for you to remove the plugin page at dokuwiki.org?

**Comment by Klap-in** [comment]
See https://www.dokuwiki.org/teams:extensioncleanup for this list in wiki format.
Also I have added automatically links to list above, but please take care whether the url points to the logic page.

**Comment by LarsGit223** [comment]
What do we do with plugins that simply do not have a download repository? E.g. the tab plugin is very small and simple and has the complete source code on the plugin page. Should we contact the maintainers and try to ask them to create one (preferably on github)?

**Comment by selfthinker** [comment]
I vote against deleting the extension page completely. If someone installed an extension which is now outdated, they should be able to learn what happened to it and be able to find potential alternatives.
Just removing the syntax with the dashes should be enough. For example,
```
---- plugin ----
description: This is the description of the plugin.
author     : John Smith
lastupdate : 2008-04-25
[...]
----
```
could be taken out of the repo by simplifying it like this:
```
* description: This is the description of the plugin.
* author     : John Smith
* lastupdate : 2008-04-25
[...]
```

**Comment by leeyc0** [comment]
@LarsGit223  go ahead to remove niconico plugin on plugin page

**Comment by LarsGit223** [comment]
I vote for deletion of plugin pages which are deprecated and unmaintained for a long time (only if they do not even have a proper repo. somewhere). Especially if the plugin page also points to an actual plugin as a replacement.

IMHO the age of DokuWiki is a problem in this case. I guess there are quite a few unmaintained plugins and pages and these don't make browsing on dokuwiki.org nicer. It's not so good if a new user searches for a plugin for functionality x and then has to click himself through a number of unmaintained probably incompatible plugins.

**Comment by micgro42** [comment]
Fixed download-link of wikicalendar plugin

**Comment by selfthinker** [comment]
> I guess there are quite a few unmaintained plugins and pages and these don't make browsing on dokuwiki.org nicer. It's not so good if a new user searches for a plugin for functionality x and then has to click himself through a number of unmaintained probably incompatible plugins.

When you delete the `---- plugin ----` bits, the plugin won't be findable anymore via the plugin page or the extension manager. The only way people could find it is via Google or DokuWiki's own search.
I guess it would be good to know how people generally discover plugins.

**Comment by Klap-in** [comment]
Some extension pages are clear meaningless and could be removed, but there is a serieus group of pages that is semi-useful. For example to provide people that still have the extension installed with information, or to show history of the old plugins etc. 

My feeling is that removing the entry blocks is just a trick to hide them from extension list at template/plugins pages and from the extension manager. For these extensions some layout and behaviour changes could be useful. 

At the dokuwiki.org/plugins dokuwiki.org/template pages the list is already filtered with following criteria:
- extensions with tag `!obsolete` are hidden
- extensions with any security issue are hidden
- extensions without download url are hidden (only the bundled plugins could have no download url)

My proposal:
1. hide in the extension manager:
    - extensions with the `!obsolete` tag
    - extensions without download url (with exception for bundled plugins) (these are not installable via extension manager)

2. And to change the layout of the entry blocks at the plugins and template page if 
   - the extension is `!obsolete`, 
   - or had no download url, 
   - or has een security issue.
(proposed layout change: lightgrey text, and adding explanation that it is not shown in extension manager due to !obsolete tag or the missing downloadurl )

**Comment by splitbrain** [comment]
To be honest, I would prefer to simply delete obsolete pages. The amount of people for whom these pages would theoretically be useful is getting smaller everyday (and is very small already). OTOH those pages are still found in searches via Google and DokuWiki but provide absolutely no value to users who not already have them installed. Instead they project an image of DokuWiki having a bunch of broken extensions. I would prefer to focus on our working ecosystem and not keeping the cruft with us.

**Comment by LarsGit223** [comment]
I agree to Andi. Maybe if we see candidates for removal let's have a vote for it. Also let's ask the author what he/she thinks. If like for plugin niconico the author agrees to remove it, then IMHO we should do it.

Only exception should be plugins which show a significant usage. But if that happens that also could mean that there are some old installations out there which might have issues because of unmaintained deprecated software (performance, stability, security issues...).

IMHO really old plugins can be a problem. There is some time when you need to get rid of old things.

Also, if e.g. users only don't update DokuWiki and plugins because some old plugin doesn't work with a newer version than that is a chance for plugin developers to notice it and probably work on it. Otherwise such "landmines" will lie out there forever.

**Comment by T100D** [comment]
I vote on deleting, and if possible putting a time criteria on it somehow.
It would put a lot of more value on the plugins and templates that are really and regularly used imho.

**Comment by selfthinker** [comment]
I wouldn't mind deleting so much if only there was a way to keep at least one old revision. But they are currently deleted after 14 days on dokuwiki.org. :-/

**Comment by Klap-in** [comment]
What is 14 days?
Revisions of older removed  pages can still be brought back, did that several times these days.

Or is 14 days just the length of the global changelog? That is easy to expand, it isn't?

**Comment by mprins** [comment]
I've updated [geophp](https://www.dokuwiki.org/plugin:geophp)

**Comment by splitbrain** [comment]
As @Klap-in mentioned, we do not delete old revisions at DokuWiki and I would keep it that way for the plugin pages we remove.

So I think consensus in this thread is to delete obsolete pages.

**Comment by selfthinker** [comment]
Oh, sorry, I remember we changed that a couple of years ago when I complained about the same thing. We used to delete them but I just double checked and found we don't anymore, and then I remembered: It was changed because we lost some valuable content of standard documentation pages back then because some troll deleted them and when we wanted to resurrect them, they were already completely gone.
Okay, deleting is not as bad then. :+1:

**Comment by MvErven** [comment]
Okay, here just my two cents:
Why not split them? Moving plugins older then 3 or 4 years to an archive? When searching plugins I personally don't search for older plugins. Mostly based on popularity or date.

**Comment by LarsGit223** [comment]
There are quite a lot plugin pages which have no repository but the source code on the plugin page as a listing. Should we maybe define an explicit tag like ```norepo``` or ```sourceonpage```? This would enable automatic checks to not throw a false positive for this pages.

**Comment by Klap-in** [comment]
Is my impression right that these plugins, which have code on their wiki page, are mainly old plugins?
At times these plugins were created, online repositories like github were not common. So not used.

I think for plugin authors moving to online repositories add a lot of benefits in ways of sharing updates and tracking issues. (of course also a certain burden if you have to learn it from scratch, but learning it will help people also a lot in other code contributions, so I think it is worth.. Further platforms like github are good documented, so a doable hurdle IMHO...)

If plugins don't offer a download url, it is cumbersome for wiki admins to add such plugins to their wiki, because these are less/not visible or not useful via Extension Manager and online listing, further  they need a lot additional manual steps to install. Therefore I expect these plugins are today unpopular. 

My proposal is: hide plugins without download url completely from Extension Manager and online listing. Add an automatic notice at the plugin page to explain this (to educate (new) authors to make improvements...).

At the moment I'm preparing a pull request for completely hiding extensions marked with `!obsolete` tag. With explanation notice as well. (I will share pointer if it is there). If appreciated, I can combine it with this proposal.

**Comment by LarsGit223** [comment]
> Is my impression right that these plugins, which have code on their wiki page, are mainly old plugins?
> At times these plugins were created, online repositories like github were not common. So not used.

Yes, I think so.

> I think for plugin authors moving to online repositories add a lot of benefits in ways of sharing updates and tracking issues. (of course also a certain burden if you have to learn it from scratch, but learning it will help people also a lot in other code contributions, so I think it is worth.. Further platforms like github are good documented, so a doable hurdle IMHO...)

Well I fear that there is not much interest of the authors to invest the required time in such old plugins. That plugins often haven't been touched for 10 years or more. I will try to get in contact with the authors for this plugins too, but often there is a invalid mail or simply no reaction.

**Comment by Klap-in** [comment]
Popularity score for plugins without download url can be found here: https://www.dokuwiki.org/teams:plugins_gardening#plugins_missing_download_button

**Comment by LarsGit223** [comment]
To what does the number under ```Popularity``` relate to? Isn't it a percentage usually?

**Comment by Klap-in** [comment]
The Popularity score is a counter based at the times the plugin availability was submitted via the popularity plugin.
See for the numbers the last column of: https://www.dokuwiki.org/plugins?pluginsort=^c#extension__table
(the numbers are calculated by [cron.php](https://github.com/splitbrain/dokuwiki-plugin-pluginrepo/blob/master/cron.php) of the pluginrepo. It counts the number of submissions in 2 years)

**Comment by LarsGit223** [comment]
A little update:
I have  adopted the webcomics plugin, see https://www.dokuwiki.org/plugin:webcomics.

I suggest to eventually remove some deprecated and/or similar plugin pages like:
- https://www.dokuwiki.org/plugin:dokuwiki-webcomics
- https://www.dokuwiki.org/plugin:garfield
- https://www.dokuwiki.org/plugin:dil
- https://www.dokuwiki.org/plugin:garfield
- https://www.dokuwiki.org/plugin:xkcd
